name: test

on: [push, pull_request]

jobs:
  build:
    name: "build on ${{ matrix.os }} (node version ${{ matrix.node-version }})"

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [12.x, 14.x, 16.x]

    runs-on: ${{ matrix.os }}

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - run: npm ci
    - run: npm run build
    - run: npm test
    - name: Publish
      if: "contains(github.event.head_commit.message, 'Release')"
      env:
        GITHUB_TOKEN: ${{ secrets.NODE_PRE_GYP_GITHUB_TOKEN }}
      run: npm run upload-binary
