name: test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - run: npm ci
    - run: npm run build
    - run: npm test
    - name: Publish
      if: "contains(github.event.head_commit.message, '[publish binary]')"
      run: |
        COMMIT_MESSAGE=$(git log --format=%B --no-merges -n 1 | tr -d '\n') \
        npm run upload-binary
